public class DiscussionWidgetNewDiscussionsTest {

   public static testMethod void testDiscussion() {
   DiscussionWidgetNewDiscussionsController dis = new DiscussionWidgetNewDiscussionsController();
   DiscussionWidgetNewDiscussionsController.Topics topics = new DiscussionWidgetNewDiscussionsController.Topics();
   //List<DiscussionWidgetNewDiscussionsController.Topics> list = dis.getNewDiscussionTopics();
   //System.assert(list.size()==0,'La lista no tiene elementos');	
	  
   } 	

}