@isTest private class GoogleDocsControllerTest {
	
//	public static testMethod void test() { 
		
		
//		GenerateEnvironmentTest.gen(); 
//		Test.startTest();
		
//			GoogleDocsController gDoc = new GoogleDocsController();
			
			// This is the Google Apps account domain.
			// %%%%%% 			IMPORTANT 		 %%%%%
//			String gDocsDomain = 'a/timbasoftware.com/';
			// This is the Google Apps account domain.
			
//			GoogleDoc newDoc = new GoogleDoc();
//			newDoc.Name = 'Foo Google Document';
//			newDoc.ParentId = GenerateEnvironmentTest.newTeam.Id;
//			newDoc.Url = 'https://docs.google.com/' + gDocsDomain + 'Doc?docid=fooId';
//			insert newDoc;
//			
//			GoogleDoc newSS = new GoogleDoc();
//			newSS.Name = 'Foo Google Spreadsheet';
//			newSS.ParentId = GenerateEnvironmentTest.newTeam.Id;
//			newSS.Url = 'https://spreadsheets.google.com/' + gDocsDomain + 'Doc?docid=fooId';
//			insert newSS;
			
//			GoogleDoc newPres = new GoogleDoc();
//			newPres.Name = 'Foo Google Presentation';
//			newPres.ParentId = GenerateEnvironmentTest.newTeam.Id;
//			newPres.Url = 'https://docs.google.com/' + gDocsDomain + '/Presentation?docid=fooId';
//			insert newPres;
			
//			gDoc.setSidebar(true);
//			gDoc.getSidebar();
			
//			gDoc.setTeamId(GenerateEnvironmentTest.newTeam.Id);
//			gDoc.getTeamId();
			
//			gDoc.getGoogleDocuments();
//			gDoc.getGoogleDocumentsCount();
			
			// TEST Documents INNER CLASS
//			GoogleDocsController.Documents docs = new GoogleDocsController.Documents();
//			docs.getId();
//			docs.getDocType();
//			docs.getName();
//			docs.getUrl();
//			docs.getUpdated();
//			docs.getAuthor();
			
			// SESSION TOKEN
//			gDoc.getSessToken();
//			System.currentPageReference().getParameters().put('sesstoken', 'FooToken');
//			gDoc.exchangeRequestToken();
			
			// GENERATE GOOGLE DOCS LIST
//			gDoc.setGoogleDocuments();
			
			// Delete Google Doc
//			gDoc.setDelDoc(newDoc.Id);
//			System.currentPageReference().getParameters().put('delDoc', newDoc.Id);
//			gDoc.deleteGoogleDoc();
		
//		Test.stopTest();
//	}
	
	
}