@isTest private class GoogleDocsControllerTest {
	
	/*
	public static testMethod void test() { 
	    
		GenerateEnvironmentTest.gen();
		Test.startTest();
		
			GoogleDocsController gDoc = new GoogleDocsController();
			
			// This is the Google Apps account domain.
			// %%%%%% 			IMPORTANT 		 %%%%%
			String gDocsDomain = 'a/timbasoftware.com/';
			// This is the Google Apps account domain.
			
			GoogleDoc newDoc = new GoogleDoc();
			newDoc.Name = 'Foo Google Doc';
			newDoc.ParentId = GenerateEnvironmentTest.newTeam.Id;
			newDoc.Url = 'https://docs.google.com/' + gDocsDomain + 'Doc?docid=fooId';
			insert newDoc;
			
			gDoc.setSidebar(true);
			gDoc.getSidebar();
			
			gDoc.setTeamId(GenerateEnvironmentTest.newTeam.Id);
			gDoc.getTeamId();
			
			gDoc.getGoogleDocuments();
			gDoc.getGoogleDocumentsCount();
			
			// TEST Documents INNER CLASS
			GoogleDocsController.Documents docs = new GoogleDocsController.Documents();
			docs.getId();
			docs.getDocType();
			docs.getName();
			docs.getUrl();
			docs.getUpdated();
			docs.getAuthor();
			
			// SESSION TOKEN
			gDoc.getSessToken();
			System.currentPageReference().getParameters().put('sesstoken', 'FooToken');
			gDoc.exchangeRequestToken();
			
			// GENERATE GOOGLE DOCS LIST
			gDoc.setGoogleDocuments();
			
			// Delete Google Doc
			gDoc.setDelDoc(newDoc.Id);
			System.currentPageReference().getParameters().put('delDoc', newDoc.Id);
			gDoc.deleteGoogleDoc();
		
		Test.stopTest();
	}
	
	*/
	
}